export const SET_USER_INFO = 'SET_USER_INFO ';
export const SET_VEHICLES = 'SET_VEHICLES';
export const ADD_NEW_VEHICLE = 'ADD_NEW_VEHICLE';

// export const SELECT_VEHICLE = 'SELECT_VEHICLE';
// export const DELETE_VEHICLE = 'DELETE_VEHICLE';
// export const DESELECT_VEHICLE = 'DESELECT_VEHICLE';
// export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';
